//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirBuster.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirBuster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _241180672_704377ffc2_o {
            get {
                object obj = ResourceManager.GetObject("241180672_704377ffc2_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a admin/
        ///sadmin/
        ///admins/
        ///kadmin/
        ///_admin/
        ///admincp/
        ///myadmin/
        ///admin.py
        ///cmsadmin/
        ///wp-admin/
        ///admin.db
        ///admin.htm
        ///admin.ini
        ///admin.asp
        ///admin.ctp
        ///shopadmin
        ///admin.tpl
        ///com_admin
        ///admin_img
        ///admin.php
        ///admin.txt
        ///admin.xml
        ///admin_vote
        ///admin_menu
        ///Phpmyadmin
        ///e107_admin
        ///adminpanel
        ///adminfiles
        ///admin2.php
        ///admin.html
        ///admins.php
        ///admin.php3
        ///admin.aspx
        ///_admin.php
        ///admin1.php
        ///admin.thtml
        ///admin_users
        ///admin.rhtml
        ///xgadmin.asp
        ///pnadmin.php
        ///admin_setup
        ///blocksadmin
        ///administrar
        ///admin.phtml
        ///myadmin.asp        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string AdminAndSetup {
            get {
                return ResourceManager.GetString("AdminAndSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a index/
        ///images/
        ///download/
        ///2006/
        ///news/
        ///crack/
        ///serial/
        ///warez/
        ///full/
        ///12/
        ///contact/
        ///about/
        ///search/
        ///spacer/
        ///privacy/
        ///11/
        ///logo/
        ///blog/
        ///new/
        ///10/
        ///cgi-bin/
        ///faq/
        ///rss/
        ///home/
        ///img/
        ///default/
        ///2005/
        ///products/
        ///sitemap/
        ///archives/
        ///1/
        ///09/
        ///links/
        ///01/
        ///08/
        ///06/
        ///2/
        ///07/
        ///login/
        ///articles/
        ///support/
        ///05/
        ///keygen/
        ///article/
        ///04/
        ///03/
        ///help/
        ///events/
        ///archive/
        ///02/
        ///register/
        ///en/
        ///forum/
        ///software/
        ///downloads/
        ///3/
        ///security/
        ///13/
        ///category/
        ///4/
        ///content/
        ///14/
        ///main/
        ///15/
        ///press/
        ///media/
        ///templates/
        ///s [stringa troncata]&quot;;.
        /// </summary>
        internal static string All_Directory {
            get {
                return ResourceManager.GetString("All_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a common
        ///CVS
        ///root
        ///Entries
        ///lang
        ///home.php
        ///setup.php
        ///install.txt
        ///default
        ///init.php
        ///Repository
        ///en.php
        ///.project
        ///admin
        ///FCKeditor
        ///list.php
        ///templates_c
        ///AUTHORS
        ///help.php
        ///style
        ///fck_about
        ///fck_about.html
        ///fck_link.html
        ///fck_paste.html
        ///fckdialog.html
        ///fckeditor.html
        ///function.config_load.php
        ///function.debug.php
        ///function.eval.php
        ///function.fetch.php
        ///modifier.nl2br.php
        ///modifier.strip_tags.php
        ///modifier.wordwrap.php
        ///shared.escape_special_chars.php
        ///flash
        ///News.php
        ///Mysql.php
        ///languages
        ///phpinfo.php
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string All_File {
            get {
                return ResourceManager.GetString("All_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a init.php
        ///config.php
        ///get.php
        ///install.php
        ///db.sql
        ///api.php
        ///portal.php
        ///c/
        ///images/
        ///includes/
        ///includes/mysql.php
        ///includes/servers.php
        ///includes/config.php
        ///includes/lib.php
        ///includes/member.php
        ///userpanel/
        ///userpanel/add_user.php
        ///userpanel/user_stats.php
        ///userpanel/user_stats.php
        ///userpanel/profile.php
        ///phpmyadmin/
        ///templates/
        ///templates/login.php
        ///templates/footer.php
        ///templates/register.php
        ///admin/
        ///admin/categories.php
        ///admin/servers.php
        ///admin/update.php
        ///admin/database.php
        ///admin/users.php
        ///admin/ [stringa troncata]&quot;;.
        /// </summary>
        internal static string xtreamcodes {
            get {
                return ResourceManager.GetString("xtreamcodes", resourceCulture);
            }
        }
    }
}
